# Subworkflows (reusable workflows) must be in the .github/workflows folder
name: 'Build App'
description: 'Build the App'
inputs:
  GITHUB_TOKEN: # id of input
    description: 'The github token'
    required: true
runs:
  using: "composite"
    # Steps represent a sequence of tasks that will be executed as part of the job
  steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: actions/setup-java@v1
      with:
        java-version: 23
        settings-path: ${{ github.workspace }}

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        cache-read-only: false

    - name: Test the application and analyse it
      run: gradle build test
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}